#21 person img and container fix
galerafrontend/Movies-browser pull request #20
Opened 2022-10-17 14:02 UTC by Ziko225

2022-10-18 07:55 UTC, wojciech-leksza requested changes
kafelki z aktorami działają idealnie, dokładnie o to chodziło. 😁 Zrób jeszcze to samo dla kafelek z filmami, bo z tym dalej jest problem. No i można by jeszcze pokombinować, żeby w sytuacji gdzie wyszukiwarka znajdzie mniej niż 6 osób, wszystkie ustawiałyby się od lewej zamiast na środku jak teraz. 😁

2022-10-18 07:55 UTC, wojciech-leksza commented on src/features/People/PeoplePage/Content/index.js
> +                                pictureUrl={person.profile_path? `https://image.tmdb.org/t/p/w400${person.profile_path}` : null}
daj jeszcze spację przed `?`, i fajnie by było jakbyś link `https://image.tmdb.org/t/p/w400` wrzucił do configAPi i importował gdzie trzeba, żeby w razie czego można było zmienić go w jednym miejscu 😁można też podzielić na 2 linki - w400 albo original (bo chyba tylko takie używamy).

2022-10-18 08:08 UTC, wojciech-leksza commented on src/features/People/PeoplePage/Content/index.js
> +                                pictureUrl={person.profile_path? `https://image.tmdb.org/t/p/w400${person.profile_path}` : null}
a sorki, właśnie zauważyłem że z tymi linkami to nie Twoje zadanie 😅

2022-10-19 12:27 UTC, wojciech-leksza reviewed
czekam jeszcze na to rozwiązanie z pojedynczymi kartami 😁

2022-10-19 12:27 UTC, wojciech-leksza commented on src/common/HeaderCard/styled.js
> +        padding:64px 0;
Po co są te paddingi?

2022-10-19 12:27 UTC, wojciech-leksza commented on src/common/PersonCard/styled.js
> +export const PersonName = styled.span`
czemu już nie h3? można uznać to chyba jako nagłówek karty

2022-10-19 12:27 UTC, wojciech-leksza commented on src/features/Movies/MovieDetailsPage/Content/index.js
> +                            imgUrl={movieDetails.poster_path? `https://image.tmdb.org/t/p/w400${movieDetails.poster_path}`: null}
dalej nie dajesz spacji przed pytajnikiem 😅

2022-10-19 13:40 UTC, Ziko225 commented on src/common/HeaderCard/styled.js
> +        padding:64px 0;
Jeżeli brakuje zdjęcia w PosterImage to component NoPosterIcon robi się płaskim

2022-10-19 13:43 UTC, Ziko225 commented on src/common/PersonCard/styled.js
> +export const PersonName = styled.span`
Bo w komponencie MovieDetails on już nie jest używany jako nagłówek karty, chyba 😄

2022-10-19 16:16 UTC, wojciech-leksza approved these changes
Jeszcze w kilku miejscach brakuje tej spacji przed pytajnikiem, ale ogólnie wszystko wygląda ok :D

2022-10-19 16:16 UTC, wojciech-leksza commented on src/common/HeaderCard/styled.js
> +        padding:64px 0;
można było zrobić `min-height`, ale tak też jest chyba dobrze 😄

2022-10-19 16:16 UTC, wojciech-leksza commented on src/common/PersonCard/styled.js
> +export const PersonName = styled.span`
No właśnie chyba wszędzie jest nagłówkiem :D

2022-10-21 11:14 UTC, galerafrontend approved these changes
Mam wrażenie że w niektórych miejscach robiliśmy to samo ale w inny sposób zobaczymy jak wyjdzie z konfliktami. Ogólnie dobra robota :D

2022-10-21 11:14 UTC, galerafrontend commented on src/common/HeaderCard/styled.js
> +        padding:64px 0;
ja tutaj zmieniłem noPosterIcon z svg na png żeby nie trzeba było ustawiać na sztywno szerokości i wysokości

2022-10-21 18:05 UTC, merged