#22 api corrected
galerafrontend/Movies-browser pull request #23
Opened 2022-10-22 10:42 UTC by wojciech-leksza

Naprawiłem api, żeby nie pokazywało filmów przed ładowaniem i usunąłem napis przy ładowaniu bez query, tak jak chciał Krzysiek 😁 Przy okazji rozwiązał się problem z błędem "total_pages". 😎

2022-10-23 09:13 UTC, Ziko225 requested changes
Jest dobrze, tylko że error "total_pages". nadal jest. Czekamy na rozwiązanie 😄

2022-10-23 10:26 UTC, wojciech-leksza commented
> Jest dobrze, tylko że error "total_pages". nadal jest. Czekamy na rozwiązanie 😄

rozwiązanie dodane 😁

2022-10-23 20:55 UTC, galerafrontend approved these changes
Dobra koncepcja i elegancko wykonane zadanie

2022-10-23 20:55 UTC, galerafrontend commented on src/features/Movies/saga.js
> +    yield takeLatest(setPage.type, setPageHandler);
Dobrze, że to rozdzieliłeś :D dobry pomysł

2022-10-24 09:16 UTC, Ziko225 approved these changes

2022-10-24 09:17 UTC, merged